### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [msekoranja/emsc-hacs-repository#1]
**Is your feature request related to a problem? Please describe.**
If you want, I can add some advanced CI to your repo.

**Describe the solution you'd like**
Let me know if you want a PR.

**Describe alternatives you've considered**
- Do you want to enable auto-formatting whenever pushed?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Additional context**

**Comment by msekoranja** [comment]
Yes, please.

**Comment by KTibow** [comment]
Sure! Would you mind answering some of the questions in the bullet points? Thanks.

**Comment by msekoranja** [comment]
No, no auto-formatting. Checks are OK, manually stating formatting too, however auto-format + commit not.
What do you mean by packages? .zip release?

I have updated the docs to show some GUI images. There is already a directory w/ logo and icon in HA brands repo.

**Comment by msekoranja** [comment]
ps I need 3 reviews to get this into the HACS default repository. Without this it will not get much users. How can I get these reviews?

**Comment by KTibow** [comment]
> What do you mean by packages? .zip release?

It's the difference between me adding a file that references another GitHub repo with the code for the checks, and me pasting that code into your repo.

> How can I get these reviews?

You don't *need* them. You just need to wait for HACS's maintainer to look at all of the repos (they do it in bulk).

**Comment by msekoranja** [comment]
No need.
