### ISSUE TITLE
Any Near Realtime websocket plans?

### ISSUE THREAD

**Issue by febalci** [msekoranja/emsc-hacs-repository#3]
I have been waiting for this for a long time, thanks for all the work. I was also planning to work on EMSC seismicportal Near Realtime Websocket connection custom component [https://www.seismicportal.eu/realtime.html](url)

My plans were to put Radius1, MAgnitude1, Radius2 and Magnitude2 parameters in configuration.yaml. Inform me all earthquakes that are larger than Magnitude1 and within Radius1 and that are larger than Magnitude2 in Radius2. So; R1=100km M1=3.5 and R2=1.000km M2=5.0 would be a nice choice for the earthquakes i can feel and the serious eqs my relatives will feel. 

Anyhow, is there any plans for you to work on websocket Near Realtime? Thanks again...

**Comment by msekoranja** [comment]
Hi!

your ideas are good indeed!
However, I do not have any plans in the near future for future development.

Cheers,
Matej
