### ISSUE TITLE
Deprecation warning in 2021.12.2

### ISSUE THREAD

**Issue by ejpenney** [msekoranja/emsc-hacs-repository#4]
Hi,

I'm seeing this in 2021.12.2:

`Entity sensor.earthquakes (<class 'custom_components.emscrss.sensor.EMSCRSSServiceSensor'>) implements device_state_attributes. Please report it to the custom component author.`

So, this is me notifying the custom component author.

**Comment by ejpenney** [comment]
Since this is such an easy change, I went ahead and made a PR: https://github.com/msekoranja/emsc-hacs-repository/pull/5

**Comment by msekoranja** [comment]
Merged. Should be fine now. Let me know if there are any other problems. Thanks!
